### ISSUE TITLE
1.1.2 Release on pip

### ISSUE THREAD

**Issue by gpminsuk** [onnx/onnxmltools#105]
Hi, when I check onnxmltools package from pip, it shows version 1.0.0.0.
But I think the latest version is 1.1.2.0. How can I get 1.1.2.0?
I am new to python so I should be missing something.

Any help much appreciated!

pip show onnxmltools
Name: onnxmltools
Version: 1.0.0.0
Summary: Converts Machine Learning models to ONNX
Home-page: https://github.com/onnx/onnxmltools
Author: Microsoft Corporation
Author-email: onnx@microsoft.com
License: MIT License
Location: c:\users\mika\appdata\local\programs\python\python36\lib\site-packages
Requires: numpy, protobuf, onnx
Required-by:

**Comment by tiagoshibata** [comment]
Suggestion: If you want the latest, `pip install git+git://github.com/onnx/onnxmltools.git#egg=onnxmltools` will clone the package from Git and install it.
