### ISSUE TITLE
LightGBM is not a dependency but import fails for sklearn converters.

### ISSUE THREAD

**Issue by xadupre** [onnx/onnxmltools#131]
See onnxmltools/convert/sklearn/_parse.py which contains the instruction from lightgbm import LGBMClassifier, LGBMRegressor.

**Comment by wschin** [comment]
Do you mean that requirement.txt should be modified for adding LightGBM, scikit-learn, keras, and tensorflow?

**Comment by xadupre** [comment]
I fixed it by separating sklearn and lightgbm into two separate folders.
