### ISSUE TITLE
Are the exported models intended to work with Windows.AI.MachineLearning?

### ISSUE THREAD

**Issue by pinkwerks** [onnx/onnxmltools#138]
Hi, I'm attempting to load model3.onnx (attached):
using Windows.AI.MachineLearning;

I get this error:
_model = await LearningModel.LoadFromStorageFileAsync(file);
Output:
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 300}
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 300}
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.CoreLib.dll but was not handled in user code
WinRT information: [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 300}
Unspecified error
[TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 300}

I'm not sure where to begin? I have another .onnx model file that loads okay with the same code. (also attached)
[models.zip](https://github.com/onnx/onnxmltools/files/2421210/models.zip)

**Comment by pinkwerks** [comment]
To clarify, I wasn't sure if the file was invalid. Nutron was able to view them both so.ill assume this is a loader problem with windows.ai.

**Comment by youngkim93** [comment]
Hi, thank you reporting your problem. In general, the fact that you can view the model in Netron does not imply that it can run on Windows.AI.Machinelearning platform. In the future, we will be providing a tool called winmltools that could potentially provide more information about validity of onnx model for Windows platform.

Having said that, we would still love to help this scenario! Were you able to solve this problem yet?

**Comment by youngkim93** [comment]
It looks to me like the model does not have a right permutation attribute for transpose operator. Input Shape of transpose is 2 dimensions while permutation is specifying 4 dimensions. Is this model coming from the onnxmltool?

**Comment by pinkwerks** [comment]
Hi, thanks for the help!

This model was created in Keras. Then exported using onnxmltools. I'm unclear if this is a translation problem, or the Windows.AI API is having an issue parsing something valid. FWIW the model "just worked" in keras. This is my model in keras and how I'm exporting it.

```
def baseline_model(num_classes=12, num_dim=33):
    # create model
    model = Sequential()   
    model.add(Dense(num_classes * num_classes * num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes * num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes, activation='softmax'))   
    opt = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
    model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
    return model

model4 = baseline_model()
onnx_model = onnxmltools.convert_keras(model4)

# Save as protobuf
onnxmltools.utils.save_model(onnx_model, 'model4.onnx')
```
And from this example:
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: [TypeInferenceError] Invalid attribute perm {0, 3, 1, 2}, input shape = {1, 1728}

Again, I'm not enough of an expert to understand where this is going bonkers. Thanks for looking.

**Comment by youngkim93** [comment]
Thanks for that snippet. This will help us debug what is going on. My initial guess is that this problem is coming from the onnxmltools since this look like an invalid onnx file. I will update you with more details.

**Comment by pinkwerks** [comment]
The linked item was closed - does that mean this issue was resolved?

**Comment by jiafatom** [comment]
@pinkwerks , I just tested your snippet, and it works well now. Please try https://github.com/onnx/keras-onnx because we have moved the keras2onnx converter there. See Readme.md there. I just use your snippet and use ```keras2onnx.convert_keras``` to convert keras model.
```
def baseline_model(num_classes=12, num_dim=33):
    # create model
    model = Sequential()   
    model.add(Dense(num_classes * num_classes * num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes * num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes, input_dim=num_dim))
    model.add(BatchNormalization());
    model.add(Activation('tanh'))
    model.add(Dense(num_classes, activation='softmax'))   
    model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
    return model

model4 = baseline_model()
# use keras2onnx.convert_keras here
onnx_model = keras2onnx.convert_keras(model4, "model4")
onnx.save_model(onnx_model, 'model4.onnx')

content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
x = np.random.uniform(-0.5, 0.5, size=(1, 33)).astype(np.float32)
x = x if isinstance(x, list) else [x]
feed = dict([(input.name, x[n]) for n, input in enumerate(sess.get_inputs())])
pred_onnx = sess.run(None, feed)
```
and it gives me the same result as original keras prediction. Please let us know if you have further questions.

**Comment by jiafatom** [comment]
Resolved -- see my comments above, close the issue. Feel free to reopen if there are further concerns.
