### ISSUE TITLE
Protobuf error converting CoreML to ONNX

### ISSUE THREAD

**Issue by jsigee87** [onnx/onnxmltools#139]
I have a test CoreML model that is 475 MB in size, a quick script to convert it to ONNX fails with the following error. 

Is there a size limitation or something I can do on the CoreML side? I hope to use ONNX to convert CoreML models to other formats so I can do model compression. 

Can I do without the .json representation?

```
[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:164] Cannot allocate buffer larger than kint32max for StringOutputStream.
Traceback (most recent call last):
  File "coreml_to_tf.py", line 16, in <module>
    onnxmltools.utils.save_text(onnx_model, onnx_path + '.json')
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnxmltools/utils/main.py", line 86, in save_text
    f.write(str(model))
ValueError: Unable to convert message to str
```

The script to reproduce this is:
```
#Quick converter

import onnx
import onnxmltools
import coremltools

model_path = 'tests/testmodel.mlmodel'
onnx_path = 'tests/testmodel'
model_name = 'Test Model'

# coreml -> onnx
coreml_model = coremltools.utils.load_spec(model_path)
onnx_model = onnxmltools.convert_coreml(coreml_model, model_name)
onnxmltools.utils.save_text(onnx_model, onnx_path + '.json')
onnxmltools.utils.save_model(onnx_model, onnx_path + '.onnx')
```

**Comment by prasanthpul** [comment]
You don't need the JSON line - that's only if you want a human readable form of the file. The ".onnx" file is what you need. If you remove the JSON line, do you still run into the issue?

**Comment by jsigee87** [comment]
Apologies for not updating this, without the json line it runs fine. I am going to close, although I would maybe update example usage to show that it is optional.

**Comment by prasanthpul** [comment]
yes good suggestion
