### ISSUE TITLE
Flatten layer outputting incorrect values

### ISSUE THREAD

**Issue by riacheruvu** [onnx/onnxmltools#164]
I successfully converted [a Keras implementation of the Neural Collaborative Filtering model ](https://github.com/hexiangnan/neural_collaborative_filtering) to Onnx using OnnxMLTools, but the Flatten layer of the converted Onnx model is outputting incorrect values (for example, the Onnx model outputs        _dim_value: 1_) compared to the original Keras model (for example, the Keras model outputs _(None, 8)._). 

The Onnx model I am using is available here: https://www.dropbox.com/s/fwiaqk6xy0n3z6o/NCF.onnx?dl=0 

I'm not sure if this is a bug with the converter or if there are any problems with the Onnx model itself. Some relevant details include that I used Python 2.7.15, Keras 2.2.4, and OnnxMLTools 1.2.2.0129 when converting the Keras model to Onnx. 

Could someone please advise on this issue? I can share more details if needed.

I've included a picture below of the Keras model:

![model_plot](https://user-images.githubusercontent.com/22090501/48098391-d1465380-e1d9-11e8-90d8-a8e8a6a0c8cf.png) 

I'm also including a picture of the outputs for the Flatten layers for the Onnx model:

![onnx_flatten](https://user-images.githubusercontent.com/22090501/48098553-5e89a800-e1da-11e8-85be-a4b5f98403dd.png)

Thank you!

**Comment by wenbingl** [comment]
Did you try to run the onnx model to see whether the final result is correct? The shape of tensor in onnx could be optional.

**Comment by riacheruvu** [comment]
Thank you for the response, @wenbingl. I’m sorry for the late reply, I was trying to setup the Onnx backends in order to run the Onnx models; exporting the Onnx model to Tensorflow is causing errors (although onnx.checker.check_model passes), but I plan to try running the Onnx model with the Caffe backend as well. For my application, the shape of the tensors is important, so I wanted to confirm if there’s anything I can do to adjust the output of the Flatten layer or figure out why the Flatten layer for the Onnx model outputs different values compared to the Keras model. Thank you for the help.

**Comment by prasanthpul** [comment]
To run the model, you can also use https://pypi.org/project/onnxruntime/
