### ISSUE TITLE
LightGBM regression on convert_sklearn() Pipeline

### ISSUE THREAD

**Issue by little-eyes** [onnx/onnxmltools#175]
I know we have moved LightGBM converter to its own namespace, but I strongly believe that we should keep the sklearn `Pipeline` convert work with LightGBM. An example below:

```python
clf = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore')),
    ('classifier', lgb.LGBMClassifier(objective="binary"))
])

clf.fit(X_train[categorical_features], y_train)
clf.score(X_test[categorical_features], y_test)
model_onnx = convert_sklearn(clf, 'pipeline', [("input", StringTensorType([1, 3]))])
```

I got ValueError: No proper operator name found for '<class 'lightgbm.sklearn.LGBMClassifier'>'

**Comment by xadupre** [comment]
lightgbm converters was moved into a separate folder as it is a separate library. We should have added a warning. You can call convert_lightgbm.
