### ISSUE TITLE
Input dimensions are not compatible

### ISSUE THREAD

**Issue by maondra** [onnx/onnxmltools#195]
Hi, 

 I have exported model from Keras to ONNX (using onnxmltools). Than I tried to load and run model using CNTK. Unfortunatelly I got this message:

ValueError: Node 'Plus222' (Plus operation): Input dimensions [24 x 777 x 521 x 1] and [24 x 771 x 515 x 1] are not compatible.
Model in keras works fine.
Is it possible that something went wrong during conversion? Is it possible to convert this model?
```

    def _residual_block(inputs):
        x = Conv2D(feature_dim, (3, 3), padding="same", kernel_initializer="he_normal")(inputs)
        x = BatchNormalization()(x)
        x = PReLU(shared_axes=[1, 2])(x)
        x = Conv2D(feature_dim, (3, 3), padding="same", kernel_initializer="he_normal")(x)
        x = BatchNormalization()(x)
        m = Add()([x, inputs])

        return m

    inputs = Input(shape=(None, None, input_channel_num))
    x = Conv2D(feature_dim, (3, 3), padding="same", kernel_initializer="he_normal")(inputs)
    x = PReLU(shared_axes=[1, 2])(x)
    x0 = x

    for i in range(resunit_num):
        x = _residual_block(x)

    x = Conv2D(feature_dim, (3, 3), padding="same", kernel_initializer="he_normal")(x)
    x = BatchNormalization()(x)
    x = Add()([x, x0])
    x = Conv2D(input_channel_num, (3, 3), padding="same", kernel_initializer="he_normal")(x)
    model = Model(inputs=inputs, outputs=x)
```
code example from: https://github.com/yu4u/noise2noise/blob/master/model.py

Thank you.

**Comment by wenbingl** [comment]
Would you like to try onnx-runtime which supports the onnx better?
https://github.com/Microsoft/onnxruntime

**Comment by maondra** [comment]
I can confirm that converted model works correctly with onnxruntime.
