### ISSUE TITLE
keras.layers.convolutional.SeparableConv2D   in Keras not implemented?

### ISSUE THREAD

**Issue by chenxian9999** [onnx/onnxmltools#197]
when convert a Keras model, i recieve this error:
ValueError: Unsupported shape calculation for operator <class 'keras.layers.convolutional.SeparableConv2D'>

**Comment by wenbingl** [comment]
SeparableConv2D layer conversion hasn't been supported yet. Will be added soon.

**Comment by wenbingl** [comment]
Added

**Comment by pGit1** [comment]
PLEASE HELP!!! 

I still get this error after pip installing onnxmltools.

My code:

`onnx_model = onnxmltools.convert_keras(m)  `

error:

`Unsupported shape calculation for operator <class 'keras.layers.convolutional.SeparableConv2D'>`

**Comment by wenbingl** [comment]
We didn't publish any pypi package recently, so you have to install the package from the GitHub source.
