### ISSUE TITLE
Quantized Core ML Model Converts to Invalid Onnx Model

### ISSUE THREAD

**Issue by TobyRoseman** [onnx/onnxmltools#202]
For the example below I used [MobileNet.mlmodel](
https://docs-assets.developer.apple.com/coreml/models/MobileNet.mlmodel) downloaded from [Working with Core ML Models](
https://developer.apple.com/machine-learning/build-run-models/), but this seems to be a problem with any quantized Core ML Model.

```python
import coremltools
import onnx
import onnxmltools

# This works fine.
coreml_model = coremltools.utils.load_spec('./MobileNet.mlmodel')
onnx_model = onnxmltools.convert_coreml(coreml_model, 'Mobile Net')
onnx.checker.check_model(onnx_model)

# Quantize the Core ML Model.
model_spec = coremltools.utils.load_spec('./MobileNet.mlmodel')
model_fp16_spec = coremltools.utils.convert_neural_network_spec_weights_to_fp16(model_spec)
coremltools.utils.save_spec(model_fp16_spec, 'MobileNet-FP16.mlmodel')

# This does not work.
coreml_model = coremltools.utils.load_spec('./MobileNet-FP16.mlmodel')
onnx_model = onnxmltools.convert_coreml(coreml_model, 'Mobile Net')
onnx.checker.check_model(onnx_model)
```

The second `onnx.checker.check_model` call, with the quantized model, gives the following error:
`ValidationError: TensorProto (tensor name: convolution_W) should contain one and only one value field.`

**Comment by wenbingl** [comment]
No, i don't think the converter supports the quantized model now.

**Comment by vinitra** [comment]
Closing this issue as onnxmltools doesn't currently support quantized CoreML models and doesn't have immediate resources to support this feature request in development. We welcome contributions from the community! Feel free to reopen this issue if there are any further developments.
