### ISSUE TITLE
initializer is not in the graph input

### ISSUE THREAD

**Issue by FrozenGene** [onnx/onnxmltools#21]
The related node in the model graph:
```graph {
  node {
    input: "input__0"
    input: "convolution.W"
    output: "MobilenetV1_MobilenetV1_Conv2d_0_convolution_0"
    name: "convolution"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
```

And when to use ONNX IR Checker
```python
import onnx
# Load the ONNX model
model = onnx.load("mobilenet.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a human readable representation of the graph
onnx.helper.printable_graph(model.graph)
```

Traceback (most recent call last):
  File "onnx_checker.py", line 6, in <module>
    onnx.checker.check_model(model)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx-1.1.1-py3.6-macosx-10.12-x86_64.egg/onnx/checker.py", line 76, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: convolution.W in initializer but not in graph input

I find https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/common/_topology.py#L635

```python
    graph = helper.make_graph(container.nodes, model_name, container.inputs, container.outputs, container.initializers)
```
Maybe we should use input_with_initializers (container.inputs + container.initializers)

**Comment by wschin** [comment]
Thanks for reporting. We notice the latest ONNX checker complains some format/attribute of the converted models. We are working on [them](https://github.com/wschin/onnxmltools/tree/fixes).

**Comment by wschin** [comment]
Fixed in PR 25. Thanks.
