### ISSUE TITLE
Need for explicit installation of Keras when tensorflow is installed

### ISSUE THREAD

**Issue by dipayan90** [onnx/onnxmltools#215]
As keras now gets bundled along with the tensorflow install. It may be a good idea to also check for `from tensorflow import keras` in addition to just `import keras` in https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/common/utils.py#L35

**Comment by wenbingl** [comment]
Thanks for your suggestion. Keras API in TF is a little different from the standalone one, and we haven't support it yet.
