### ISSUE TITLE
Coreml to onnx conversion : conversion succeeded but incorrect value on inference 

### ISSUE THREAD

**Issue by deovrat** [onnx/onnxmltools#216]
I am trying to convert a coreml model to onnx. The conversion succeeded but  predict using winml doesn't give the same values of output as coreml.

I am doing the same proprocessing for onnx that I am doing for coreml before feeding the input. The coreml model gives the correct output , while onnx outputs much lower values. Using OnnxRuntime to do inference. Am I doing something wrong in conversion ?

Model details : -
coreml model input specs : -
```
Input : - float64[None,4,320,320] . 
```
4 here is BGRM ( where M stands for mask value for each pixel ) - image size is 320 X 320 . Network is inception based.

```
Output :- float64[None,2,320,320]
```

Last layer of the network is softmax but the onnx output doesn't seem to show softmax property ie - sum of probabilities to 1.

Code that I used for conversion :- 
```
model_coreml = load_spec(coreml_model_path)
onnxmodel = onnxmltools.convert_coreml(model_coreml, 'model')
onnxmltools.utils.save_model(onnxml_model, converted_onnxml_path)
```
The output model has float32 as types of tensors. Can this be a issue ? Is there a way to convert the model into float64 from coreml.

**Comment by vinitra** [comment]
At this point, we do not support the [float64 data type](https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/common/data_types.py) in the CoreML to ONNX converter, which is likely the cause of your issue. We welcome contributions from the community!
