### ISSUE TITLE
BatchNormalization sets wrong opset version be 1, not 6

### ISSUE THREAD

**Issue by FrozenGene** [onnx/onnxmltools#22]
ONNX checker reports error of BatchNormalization operator of consumed_input. However, this is opset version 1, but we emit opset version 6 of BatchNormalization

https://github.com/onnx/onnx/blob/master/docs/Operators.md#BatchNormalization

> This version of the operator has been available since version 6 of the default ONNX operator set.
Other versions of this operator: BatchNormalization-1

our code is https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/coreml/operator_converters/neural_network/BatchNorm.py#L69:
```python
    container.add_node(op_type, inputs, outputs, **attrs)
```
We use the default parameter `op_version=1`, here we should be 6.

See the wrong information:
```
Traceback (most recent call last):
  File "onnx_checker.py", line 6, in <module>
    onnx.checker.check_model(model)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx-1.1.1-py3.6-macosx-10.12-x86_64.egg/onnx/checker.py", line 76, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Required attribute 'consumed_inputs' is missing.

==> Context: Bad node spec: input: "MobilenetV1_MobilenetV1_Conv2d_0_convolution_0" input: "BatchNormalization_scale" input: "BatchNormalization_B" input: "BatchNormalization_mean" input: "BatchNormalization_variance" output: "MobilenetV1_MobilenetV1_Conv2d_0_BatchNorm_batchnorm_add_1_0" name: "batchnorm" op_type: "BatchNormalization" attribute { name: "epsilon" f: 0 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "momentum" f: 0 type: FLOAT } attribute { name: "spatial" i: 1 type: INT } domain: "" 
```

**Comment by wschin** [comment]
Thanks. It seems to be a bug in onnx checker. As described in [onnx-1.1.2](https://github.com/onnx/onnx/blob/rel-1.1.2/docs/Operators.md#BatchNormalization), that attribute doesn't exist. I need to open another issue to discuss what the version should be under onnx repo.

**Comment by wschin** [comment]
Fixed [here](https://github.com/onnx/onnxmltools/blob/ccf3acb629d90d4a5634252951c2ea530302cc03/onnxmltools/convert/common/_apply_operation.py#L80).
