### ISSUE TITLE
CoreML to ONNX conversion failed

### ISSUE THREAD

**Issue by omer-waheed** [onnx/onnxmltools#220]
Hi, 
I am trying the example written in readme of the repo but i always end up having this error. please guide.
<img width="1218" alt="screenshot 2019-01-27 at 1 55 24 pm" src="https://user-images.githubusercontent.com/34219087/51798889-73a32f80-223b-11e9-9754-169abbd461d7.png">

this is my code 
<img width="911" alt="screenshot 2019-01-27 at 1 58 04 pm" src="https://user-images.githubusercontent.com/34219087/51798898-9fbeb080-223b-11e9-8db2-7d9f836bfef9.png">

**Comment by vinitra** [comment]
Hello @omer-waheed! It seems like you might have some [custom layers](https://developer.apple.com/documentation/coreml/mlcustommodel) on the Apple CoreML side that onnxmltools does not currently support.

**Comment by vinitra** [comment]
The coreml -> onnx conversion code from the README is correct, but the model you are trying to convert has a "customModel" operator that we cannot support during conversion.

As there has been no action for the last 2 weeks, I am closing this issue. Feel free to reopen it if there are new developments!
