### ISSUE TITLE
Combine sklearn pipeline with keras or lightgbm

### ISSUE THREAD

**Issue by NonaryR** [onnx/onnxmltools#221]
Hello! It's possible to use `pipeline` from [sklearn-onnx](https://github.com/onnx/sklearn-onnx) for preparing data and on top of that `keras` or `lightgbm` model?
It is not clear for me - which convert function I should choose fro this operation

**Comment by vinitra** [comment]
Closing issue, since it's been over a week. Please feel free to re-open this issue or open a new issue in the [sklearn-onnx](https://github.com/onnx/sklearn-onnx) repository if the linked tutorial doesn't answer your question!

**Comment by themummy** [comment]
It looks like the converter method needs to have this signature `(scope, operator, container)`. I could find the `convert_lightgbm`
@vinitra , I can see that there's a [`convert_lightgbm()`](https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/lightgbm/operator_converters/LightGbm.py#L131) method to be used with a sklearn2onnx. But I can't find a similar method for Keras. Any idea?
