### ISSUE TITLE
Support sklearn TfidfTransformer

### ISSUE THREAD

**Issue by WilliamTambellini** [onnx/onnxmltools#223]
When trying to convert a sklearn embedding a TfidfTransformer : 

text_clf = Pipeline([ 
        ('vect', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', lsvc),
    ])
    text_clf.fit(twenty_train.data, twenty_train.target) 
    onnx = convert_sklearn(text_clf, target_opset=9, name='DocClassifierCV-TfidT-LSVC', initial_types=[('input', FloatTensorType([1, 2]))])

Exception "unhandled ValueError"
No proper operator name found for '<class 'sklearn.feature_extraction.text.TfidfTransformer'>'
File: /usr/local/lib/python3.5/dist-packages/onnxmltools/convert/sklearn/_parse.py, Line: 107

Would the Tfidf vectorizer in onnx standard do the job ? 
https://github.com/onnx/onnx/blob/master/docs/Operators.md#TfIdfVectorizer

**Comment by vinitra** [comment]
Hi @WilliamTambellini! Unfortunately onnxmltools does not support Opset 9 / ONNX version 1.4 yet, and the TFIDF Vectorizer was introduced with v1.4. We are working on updating the converters to support these operators!

**Comment by WilliamTambellini** [comment]
Hello @vinitra  thank you. 
Would it be worth it to create a github issue in order to upgrade to onnx 1.4.1/opset 9 ?

**Comment by xadupre** [comment]
The latest version of sklearn-onnx should support your example. The design might change in the future as we are looking into how to handle sparse vectors.

**Comment by xadupre** [comment]
I'll close the issue as it is now related to sklearn-onnx.

**Comment by WilliamTambellini** [comment]
ok tks, I opened another ticket on sklearn-onnx.
