### ISSUE TITLE
Package documentation

### ISSUE THREAD

**Issue by rth** [onnx/onnxmltools#232]
I was not able to find the documentation for the onnxmltools python package. In particular, I was looking for the package API docs.

Clicked on several links of the readme that mention something about the documentation (mostly about the onnx) but without much success. Maybe I missed something, but it would be nice to either add it or make it more visible.

**Comment by rth** [comment]
Well actually, there is no function docstrings e.g. for [`onnxmltools.convert_sklearn`](https://github.com/onnx/onnxmltools/blob/ea574cfd8df6304db1cee30337986738cd6a0d2f/onnxmltools/convert/main.py#L55) so even reading the source code doesn't help much in understanding how a function should be used.

**Comment by rth** [comment]
https://github.com/onnx/onnxmltools/pull/190 would address some of it which would be really nice.

**Comment by xadupre** [comment]
convert_sklearn was was moved to sklearn-onnx: https://github.com/onnx/sklearn-onnx. For the time being, I test the documentation at https://xadupre.github.io/ which corresponds to the sources from github. It will more consistent soon.
