### ISSUE TITLE
Unsufficient error handling in save_model

### ISSUE THREAD

**Issue by rth** [onnx/onnxmltools#233]
`onnxmltools.save_model` does not seem to raise exceptions on incorrect input.

**Example**

```py
import onnxmltools

model = None

onnxmltools.save_model(model, './estimator.onnx')
```

**Expected result**

A Python exception with a message mentioning that `model` is not a valid onnxml model.

**Actual result**
No python exception. A printed message,
```
Failed trying to save file './estimator.onnx'.
```

**Version**

onnxmltools version 1.3.1

**Comment by vinitra** [comment]
Hi @rth! Thanks for your suggestion. I've proposed a fix in PR #242.
