### ISSUE TITLE
Can't  convert keras model with input dtype=tf.string

### ISSUE THREAD

**Issue by Kammerlo** [onnx/onnxmltools#252]
Hi,

I'm facing some issues, while converting a keras model. 
The example is just a dummy model which should demonstrate the error. (or my misunderstanding)
```
input_test = Input(shape=(1,),dtype=tf.string)
model_test = Model(input_test,input_test)
model_test.summary()
onnx_test = onnxmltools.convert_keras(model_test)
```

The output is:
`ValueError: Unable to find out a correct type for tensor Tensor("imp_root_/input_9:0", shape=(1,), dtype=string)`

Is it an onnx error or am I missing something?

Thanks!

**Comment by wenbingl** [comment]
yes, the current keras converter doesn't support string type though a few of onnx operators do accept the string input.
Do you have any practical model example to demo how the string type was used in Keras deep learning model?

**Comment by Kammerlo** [comment]
Thanks. I was trying to set up a deployment pipeline for production system. My thoughts were to accept any onnx model (to keep it easy for other model developers) and convert them to tensorflow to deploy them for example to tf serving. So I want to use onnx just as a model converter. 
In my current keras model I want to accept base64 images and do all of the work in the serving container. I know that the conversion from keras weights to tf serving is done quickly, but I was thinking of a generalized solution to be framework independent. 

But if there are operations which are currently not supported, I need to think of another solution, until onnx is providing all of the needed features.
