### ISSUE TITLE
JSONDecodeError in `onnxmltools.utils.save_text` function

### ISSUE THREAD

**Issue by Eugene-1984** [onnx/onnxmltools#273]
Hi! I am wondering about `onnxmltools.utils.save_text` function. The example on title page says:
```
# Save as text
onnxmltools.utils.save_text(onnx_model, 'example.json')
```
So I expected the output file to be a valid JSON but it is not. Here is the example code copied from the title page; MWE:
```
import onnxmltools
from keras.layers import Input, Dense, Add
from keras.models import Model

# N: batch size, C: sub-model input dimension, D: final model's input dimension
N, C, D = 2, 3, 3

# Define a sub-model, it will become a part of our final model
sub_input1 = Input(shape=(C,))
sub_mapped1 = Dense(D)(sub_input1)
sub_model1 = Model(inputs=sub_input1, outputs=sub_mapped1)

# Define another sub-model, it will become a part of our final model
sub_input2 = Input(shape=(C,))
sub_mapped2 = Dense(D)(sub_input2)
sub_model2 = Model(inputs=sub_input2, outputs=sub_mapped2)

# Define a model built upon the previous two sub-models
input1 = Input(shape=(D,))
input2 = Input(shape=(D,))
mapped1_2 = sub_model1(input1)
mapped2_2 = sub_model2(input2)
sub_sum = Add()([mapped1_2, mapped2_2])
keras_model = Model(inputs=[input1, input2], output=sub_sum)

# Convert it! The target_opset parameter is optional.
onnx_model = onnxmltools.convert_keras(keras_model, target_opset=7) 

onnxmltools.utils.save_text(onnx_model, 'example.json')

import json
with open('example.json') as f:
    json.load(f)
```
yields error: ```JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

So... can I somehow obtain a valid JSON out of converted ONNX model?

**Comment by vinitra** [comment]
Hi @Eugene-1984! Thanks for letting us know about your experience with the .save_text function.

Your call to the save_text function looks correct. We're looking into this behavior and apologize for any inconvenience caused.

**Comment by jiafatom** [comment]
@Eugene-1984 `onnx_model` is a protobuf object not a json, so json.load should not work. The function `save_text` is a legacy code, we need deprecate it, just use` save_model` to save it into binary file.

**Comment by Eugene-1984** [comment]
@jiafatomm is there any way to obtain a json-like structure from a binary model? my final goal is to get the description of the network as it is in ONNX model and yet if I load a simple mode to, say, TensorFlow, it will add tons of additional nodes and complicate the graph. I hope that onnxmltools will help me in that.

**Comment by jiafatom** [comment]
@Eugene-1984 The binary model is actually a protobuf object, so when you load the model, you get the protobuf object. So your question is actually to convert protobuf to json. This is a general question and you can find various answers on Internet. Since this is not onnx specific, onnxmltools does not support it currently.

**Comment by vinitra** [comment]
@Eugene-1984 The following script should help you get started! Remember to ``pip install protobuf`` and ``pip install onnx`` in your environment.

```
from google.protobuf.json_format import MessageToJson
import onnx
import json

model = onnx.load('model.onnx')
jsonObj = MessageToJson(model)

with open('model.json', 'w') as outfile:
    json.dump(jsonObj, outfile)

with open('model.json') as infile:
    j_model = json.load(infile)
```

j_model is now a json string with the contents of model.json. If you would prefer the output as a dictionary, please include the following line: ``dict_model = json.loads(j_model)``

See the top voted answer here: https://stackoverflow.com/questions/19734617/protobuf-to-json-in-python
