### ISSUE TITLE
Unsupported splitting criterion error in convert_lightgbm

### ISSUE THREAD

**Issue by AwasthiMaddy** [onnx/onnxmltools#285]
Hi 

I am facing below error          
`ValueError: Unsupported splitting criterion: %s. Only <=, <, >=, and > are allowed.`     
while converting my LGBMClassifier model to ONNX.  

Python - 3.7.1 installed through Anaconda on Mac
ONNX installed through `conda install -y -c conda-forge onnx`      
onnxmltools & onnxruntime installed through pip      

Any idea what is causing this error and how to resolve it?       
Does sklearn API of lightgbm is not supported for converting to onnx?

**Comment by vinitra** [comment]
Please install ONNX through PyPi (i.e. pip install onnx). The onnx package does not support Python 3.7 yet, so that might be causing some problems.

We do support conversion of lightgbm in sklearn pipelines -- see this example for more details: http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_lightgbm.html#example-lightgbm

**Comment by AwasthiMaddy** [comment]
Previously I had installed ONNX through PyPI and was facing the `AttributeError` as in below issue
https://github.com/onnx/onnxmltools/issues/135 
So as per the last comment in that issue, I uninstall ONNX and installed it back from conda and so that  error vanished but I got this error.    
Anyways let me try to install onnx in python 3.6 and try again

**Comment by AwasthiMaddy** [comment]
Hi @vinitra & @xadupre 

Even in Python 3.6, I am still facing the same error.   
  
Actually in LightGBM there is an option to specify `categorical_feature`  in `LGBMClassifier.fit` and it handles those features in different manner. In my LGB Model I had passed one feature as `categorical_feature`, after removing that feature as categorical and retraining the lightgbm model, I was able to convert it into ONNX.

**Comment by vinitra** [comment]
That's good to hear, @AwasthiMaddy! We're glad you were able to convert your LightGBM model to ONNX. LightGBM is a newly supported converter, so we're still adding additional features -- it looks like the categorical_feature functionality in LGBMClassifier.fit is not currently supported.

**Comment by vinitra** [comment]
Thanks for your feedback! Closing this issue as no further action is required.
