### ISSUE TITLE
Should we have a separate package for onnxconverter-common?

### ISSUE THREAD

**Issue by xadupre** [onnx/onnxmltools#287]

**Comment by vinitra** [comment]
We have a separate package here: https://pypi.org/project/onnxconverter-common/
However, we don't have a separate repository yet. We were considering importing onnxconverter-common as a submodule after moving the code to its own repository. Right now it seems a bit confusing for users.

cc: @wenbingl

**Comment by vinitra** [comment]
Separate repo now exists: https://github.com/microsoft/onnxconverter-common
Soon common code will be deprecated from onnxmltools.
