### ISSUE TITLE
Invalid LeakyRelu conversion from coreml to onnx

### ISSUE THREAD

**Issue by oostap1** [onnx/onnxmltools#295]
Tried to make Pull request but your license requires some extra steps from company.

Shortly:
in file **Multiply.py** , routine: **convert_multiply(scope, operator, container)**:

In line #16:
_container.add_initializer(scaler_name, onnx_proto.TensorProto.FLOAT, [], [operator.raw_operator.**add**.alpha])_

should be:

_container.add_initializer(scaler_name, onnx_proto.TensorProto.FLOAT, [], [operator.raw_operator.**multiply**.alpha])_

Otherwise LeakyRelu will be regular Relu (LeakyRelu with coef=0.0)

**Comment by vinitra** [comment]
Hi @oostap1! Thanks for filing this issue and a corresponding PR. Sorry to hear that you decided not to sign the contributor license agreement.

Proposed fix in #297.

**Comment by vinitra** [comment]
#297 is merged. Closing this issue! :)
