### ISSUE TITLE
How to edit name of layer

### ISSUE THREAD

**Issue by mrgloom** [onnx/onnxmltools#302]
Is it possible to edit name of layer in onnx?

Seems here is only part of the answer, i.e. protobuf to json
https://github.com/onnx/onnxmltools/issues/273
then we can edit json, but how to convert it back to onnx model?

**Comment by vinitra** [comment]
Hi @mrgloom! If you're interested in editing input / output layer names, you could do so with the [WinML Dashboard](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Tools/WinMLDashboard#viewing-and-editing-models).

Looks like you've found a solution in https://github.com/onnx/onnx/issues/2052 also!
