### ISSUE TITLE
sparkml GBTRegressor to onnx conversion failed

### ISSUE THREAD

**Issue by lgongmsft** [onnx/onnxmltools#305]
@jeffsaremi:

The following test failed
https://github.com/onnx/onnxmltools/blob/5e70d8e23662bee4f9c1fb25c1b0fca932843b60/tests/sparkml/test_gbt_regressor.py#L18
if I modify its input data slightly to the following:
```
        data = self.spark.createDataFrame([
            (1.5, Vectors.dense(1.0)),
            (0.5, Vectors.sparse(1, [], []))
        ], ["label", "features"])
```

**Comment by vinitra** [comment]
Hi @lgongmsft! Thanks for reporting this test case. We unfortunately do not have the bandwidth to fix this case in the GBTRegressor at the moment, but we welcome contributions from the community!
