### ISSUE TITLE
compatibility issue between onnxmltools and winmltools

### ISSUE THREAD

**Issue by lgongmsft** [onnx/onnxmltools#306]
I got the following error when trying to update the onnxmltools to its latest version (i.e., 1.4.1).
```
root@master-0:~# pip3 install -U onnxmltools
…
ERROR: winmltools 1.4.1 has requirement onnxmltools==1.4.0, but you'll have onnxmltools 1.4.1 which is incompatible.
```

**Comment by vinitra** [comment]
Hi @lgongmsft! [WinMLTools](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools) is an extension of ONNXMLTools for use with Windows ML.

At the moment, WinMLTools supports version 1.4.0 of onnxmltools. If you want to use the newest version of onnxmltools outside of winmltools, you can simply force the upgrade with the --force flag.
