### ISSUE TITLE
keras2onnx doesn't support python 2 and renders pip installation fail.

### ISSUE THREAD

**Issue by turtleizzy** [onnx/onnxmltools#311]
Env: python 2.7.15
Steps to reproduce:
```
$ pip install onnxmltools
...
Collecting keras2onnx (from onnxmltools)
  Could not find a version that satisfies the requirement keras2onnx (from onnxmltools) (from versions: )
No matching distribution found for keras2onnx (from onnxmltools)
```

**Comment by vinitra** [comment]
Hello @turtleizzy! Keras2onnx does not currently support Python 2.x, and states this requirement in keras-onnx repository's [README introduction](https://github.com/onnx/keras-onnx#introduction).

**Comment by turtleizzy** [comment]
> Hello @turtleizzy! Keras2onnx does not currently support Python 2.x, and states this requirement in keras-onnx repository's [README introduction](https://github.com/onnx/keras-onnx#introduction).
> 
> We welcome community contributions in this area!

Since [readme of onnxmltools](https://github.com/onnx/onnxmltools#Dependencies) mentioned 'tested with Python 2.7' and I don't think all onnxmltools user need support for keras2,  I suggest to make [these ml platform related dependency](https://github.com/onnx/onnxmltools/blob/master/requirements.txt) optional, otherwise installation on python 2 will not succeed.

**Comment by annaveronika** [comment]
Actually if you are using Gradient Boosting you don't need keras2. And you need onnxmltools to convert models between libraries. Many people use Python 2.7, so it would be great if pip install onnxmltools would work for python 2.7.
