### ISSUE TITLE
Converting XGBoost to Onnx using Sklearn Converter fails

### ISSUE THREAD

**Issue by francaru** [onnx/onnxmltools#334]
```python
container.add_node('TreeEnsembleClassifier', operator.input_full_names, operator.output_full_names, op_domain='ai.onnx.ml', **attr_pairs)
```
[XGBoost.py: convert (ln. 215)](https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/xgboost/operator_converters/XGBoost.py) is calling the add_node method of the container argument which has an optional argument 'name', but is later raising `RuntimeError: Parameter name cannot be empty and must be a string.` since it is not being set by the calling method.

Similar invocations of the same method in the above described file should be applied with the same fix.

Thanks

**Comment by varshakirani** [comment]
Hello @francaru ,

I am facing the same issue when I try to convert the xgboost classifier in a pipeline. Were you able to solve this or waiting for the support?

**Comment by francaru** [comment]
Hi @varshakirani,

Unfortunately no I wasn't able to solve the issue. Still waiting for the support team to apply the fix.

**Comment by varshakirani** [comment]
How have you registered the classifier?

Do you mind sharing the snippets of you code?

**Comment by francaru** [comment]
Sure thing.

```python
from onnxmltools.convert.xgboost.shape_calculators.Classifier import calculate_xgboost_classifier_output_shapes as xgboost_clf_shapes
from onnxmltools.convert.xgboost.operator_converters.XGBoost import convert_xgboost as xgboost_convert
from onnxmltools.utils import save_model as save

class XGBoostClassifierConverter(Converter):
    def to_args(self):
        cls = self.__class__
        return cls._get_type(), cls._get_identifier(), cls._calculate_output_shapes, cls._convert

    @staticmethod
    def _get_type():
        return XGBClassifier

    @staticmethod
    def _get_identifier():
        return XGBClassifier.__name__

    @staticmethod
    def _calculate_output_shapes(operator):
        xgboost_clf_shapes(operator)

    @staticmethod
    def _convert(scope, operator, container):
        xgboost_convert(scope, operator, container)

def register_custom_converters():		
    for converter in [XGBoostClassifierConverter(), ..]:
        update_registered_converter(*converter.to_args())

def save_model(pipeline, initial_types, model_name):
    # Update registered converters in sklearn
    register_custom_converters()

    # An ONNX model is achieved by converting the Sklearn Pipeline via the ONNX converters
    onnx_model = convert_sklearn(pipeline, name=name, initial_types=initial_types)

    # The model is saved
    save(onnx_model, '%s.onnx' % name)
```

As you can see, the above class has some methods which do pretty much the same thing as you described where I am registering a converter for XGBoost (note that it is in the form of a class as I am applying polymorphism across multiple converters in **'register_custom_converters'**).

Once converted, the save_model method passes the pipeline to the convert_sklearn function, and there is where the exception described in this thread is being raised.

**Comment by xadupre** [comment]
I'm adding unit tests to cover that scenario in sklearn-onnx. See https://github.com/onnx/sklearn-onnx/pull/262. Once this PR is merged, this issue will be fixed.

**Comment by varshakirani** [comment]
@francaru ,
Were you able to convert?

**Comment by msteijaert** [comment]
I have created a pull request, repairing the missing name arguments mentioned by @francaru 
https://github.com/onnx/onnxmltools/pull/337

**Comment by xadupre** [comment]
Thanks, you need to sign the CLA if you want us to merge it. The current master branch of skl2onnx also includes a modification not to raise an exception in that case.

**Comment by msteijaert** [comment]
> Thanks, you need to sign the CLA if you want us to merge it. The current master branch of skl2onnx also includes a modification not to raise an exception in that case.

I have signed the CLA, but it still shows "CLA not signed yet"

**Comment by ankit1200** [comment]
Can we close this issue since PR #337 has been merged?

**Comment by francaru** [comment]
I can confirm that this issue has been resolved. Thank you for your help.

Kind regards
