### ISSUE TITLE
Convert lightgbm to ONNX failed.

### ISSUE THREAD

**Issue by Exlsunshine** [onnx/onnxmltools#335]
## Problem
A [function ](https://github.com/onnx/sklearn-onnx/blob/11111cff60fd8d6bb69cf483fddd92ba134ca0fa/skl2onnx/common/_container.py#L318)from skl2onnx requires:
 ```
def add_node(self, op_type, inputs, outputs, op_domain='', op_version=1, name=None, **attrs):
    if name is None or not isinstance(name, str) or name == '':
            raise RuntimeError("Parameter name cannot be empty and must be a string.")
   ...
```
however a [function](https://github.com/onnx/onnxmltools/blob/fc6019467d6880afa7fa70461a014207fd1ae7ba/onnxmltools/convert/lightgbm/operator_converters/LightGbm.py#L250) in onnxmltools seems does not fit to the interface? 
```
def _parse_tree_structure(tree_id, class_id, learning_rate, tree_structure, attrs):
    ...
    container.add_node('Identity', output_name, operator.output_full_names)

```
this will always trigger an exception within skl2onnx.

## Packages version
scikit-learn==0.21.3
pandas==0.23.4
numpy==1.16.2
joblib==0.13.2
lightgbm==2.2.3
azure-storage-blob==1.3.1
onnx==1.5.0
onnxruntime==0.5.0
six
skl2onnx==1.5.1
onnxmltools==1.5.0
pyYaml

## Error sample:
Exception: Traceback (most recent call last):
E                 File "D:\doc\Codes\Projects\onnx-aml\tests\sklearn\..\..\src\converter\base_converter.py", line 135, in convert
E                   self._convert()
E                 File "D:\doc\Codes\Projects\onnx-aml\tests\sklearn\..\..\src\converter\scikitlearn_converter.py", line 75, in _convert
E                   target_opset=int(self.args.target_opset))
E                 File "D:\Program\anaconda3.201907\envs\skl_converter_1_5_1\lib\site-packages\skl2onnx\convert.py", line 138, in convert_sklearn
E                   dtype=dtype, options=options)
E                 File "D:\Program\anaconda3.201907\envs\skl_converter_1_5_1\lib\site-packages\skl2onnx\common\_topology.py", line 963, in convert_topology
E                   conv(scope, operator, container)
E                 File "D:\Program\anaconda3.201907\envs\skl_converter_1_5_1\lib\site-packages\onnxmltools\convert\lightgbm\operator_converters\LightGbm.py", line 250, in convert_lightgbm
E                   container.add_node('Identity', output_name, operator.output_full_names)
E                 File "D:\Program\anaconda3.201907\envs\skl_converter_1_5_1\lib\site-packages\skl2onnx\common\_container.py", line 342, in add_node
E                   raise RuntimeError("Parameter name cannot be empty "
E               RuntimeError: Parameter name cannot be empty and must be a string.

**Comment by Exlsunshine** [comment]
@xadupre @wschin @prabhat00155 Could please help take a look?

**Comment by xadupre** [comment]
The PR was merged. The function at https://github.com/onnx/sklearn-onnx/blob/master/tests_onnxmltools/test_lightgbm.py#L38 explains how to set up skl2onnx for lightgbm. It is still a bit complex to my opinion but it is part of CI now. Making it better requires a PR on both repos unless we move lightgbm converters into skl2onnx.

**Comment by Exlsunshine** [comment]
It seems the issue has been reported by other users, and it also has been fixed, [Run time error: Parameter name cannot be empty and must be a string. #260](https://github.com/onnx/sklearn-onnx/issues/260)
@xadupre Thanks for fixing this 👍. Do we have any ETA on releasing the master code to skl2onnx Python package?

**Comment by xadupre** [comment]
It should be soon but I don't have an ETA yet.
