### ISSUE TITLE
SeparableConv2D is converted to two Conv2D operators

### ISSUE THREAD

**Issue by kslavka** [onnx/onnxmltools#344]
![convert_input_SeparableConv2D](https://user-images.githubusercontent.com/11707452/66821996-0875c680-ef4c-11e9-803e-aaaf79a0cda8.png)
![conver_result_two_conv2d](https://user-images.githubusercontent.com/11707452/66821999-090e5d00-ef4c-11e9-9871-0b7c5cac4bae.png)

When converting Keras model that uses SeparableConv2D (depthwise separable convolution) the result is two Conv2D instead of expected one SeparableConv2D.
Is SeparableConv2D supported at all ?
I did find and old commit where  an implementation for first part of depthwise convolution as added - DepthwiseConv2D (3c556c9bb2190b06efdb6cc7c87a7215cafd7d21) 

Attaching capture from Netron utility.
The SeparableConv2D is the input - 64x3x3.
The conversion contains 2 x Conv2D.

**Comment by jiafatom** [comment]
Does the inference result match the keras model? Can you provide your model for us to debug?

**Comment by kslavka** [comment]
Yes i can share, share should i email it to ?

**Comment by kslavka** [comment]
The onnx file is used in proprietary ML framework and due to the issue raised above the inference cannot be tested at this moment.
The onnx is attached.
[DS-CNN.zip](https://github.com/onnx/onnxmltools/files/3779467/DS-CNN.zip)

**Comment by jiafatom** [comment]
Can you provide the original keras model so that we can debug from our side?

**Comment by kslavka** [comment]
You wrote "as  long as the result matches"
Can you explain how onnx regular Conv2D op achieve same result as the first part of the DepthWise separable convolution , which is convolution over each channel of an input layer. This part result in n outputs where n is number of input channel.

**Comment by jiafatom** [comment]
The conversion for DepthWise separable convolution is [here](https://github.com/onnx/keras-onnx/blob/032996f7cca19ba559fc461df9422eedc8237af1/keras2onnx/ke2onnx/conv.py#L73), check the code path for `is_separable_conv=True`. 

I wrote this logic almost one year ago - I agree the logic may not be straightforward but I implemented it an equivalent way and tested it correctly. Please check the code I mentioned to understand how it works. Thanks.
