### ISSUE TITLE
Xgboost conversion to ONNX error

### ISSUE THREAD

**Issue by chengnignzhang** [onnx/onnxmltools#349]
Hi

I am facing below error
ValueError: No proper operator name found for '<class 'xgboost.core.Booster'>'
while converting my xgboost model to ONNX. The model was trained using xgboost.

used convert_xgboost
onx = onnxmltools.convert.convert_xgboost(loaded_model, initial_types=initial_type)
Any thoughts on this error?

Does this mean xgboost.core.Booster is not supported for now?

Thanks
Chengning

**Comment by jiafatom** [comment]
cc @xadupre @prabhat00155

**Comment by xadupre** [comment]
It is not. This conversion is implemented for LightGbm and not for XGBoost. We could replicate the same trick if needed.

**Comment by ankit1200** [comment]
@xadupre do you have an example on how this would work? I'm trying to convert a xgb model to onnx and getting a similar error. 

**Error**
```ValueError: No proper operator name found for '<class 'xgboost.core.Booster'>'```

**Code**
```def convert_xgb_to_onnx(xgb_model, features):
    initial_types = [('float_input', FloatTensorType([1, len(features)]))]
    onnx_model = convert_xgboost(xgb_model,'tree-based classifier', initial_types = initial_types)
    
    with open("model_files/test_xgb.onnx", "wb") as f:
        f.write(onnx_model.SerializeToString())```

**Comment by xadupre** [comment]
I wrote a unit test to make sure it was passing: https://github.com/onnx/onnxmltools/blob/master/tests/xgboost/test_xgboost_converters.py#L188. How do you train your model?

**Comment by ankit1200** [comment]
We're using dask_xgboost: `<class 'dask_xgboost.core.XGBRegressor'>`. I've tried to convert the dask_xgboost model to onnx and the booster too: `<class 'xgboost.core.Booster'>`.
