### ISSUE TITLE
Support for XGBoost 1.0.0

### ISSUE THREAD

**Issue by victornoel** [onnx/onnxmltools#368]
This is maybe a bit early but XGBoost 1.0.0rc1 (see https://github.com/dmlc/xgboost/issues/5253) was just released and it seems that it breaks enough things so that it doesn't work when using `onnxmltools.convert.xgboost.operator_converters.XGBoost.convert_xgboost`.

This is what happens when using `convert_sklearn` on a pipeline containing an `XGBoostRegressor`:
```
 File "/home/victor/.cache/pypoetry/virtualenvs/env-51Be8MFl-py3.7/lib/python3.7/site-packages/skl2onnx/convert.py", line 138, in convert_sklearn
    dtype=dtype, options=options)
  File "/home/victor/.cache/pypoetry/virtualenvs/env-51Be8MFl-py3.7/lib/python3.7/site-packages/skl2onnx/common/_topology.py", line 963, in convert_topology
    conv(scope, operator, container)
  File "/home/victor/.cache/pypoetry/virtualenvs/env-51Be8MFl-py3.7/lib/python3.7/site-packages/onnxmltools/convert/xgboost/operator_converters/XGBoost.py", line 279, in convert_xgboost
    cls.convert(scope, operator, container)
  File "/home/victor/.cache/pypoetry/virtualenvs/env-51Be8MFl-py3.7/lib/python3.7/site-packages/onnxmltools/convert/xgboost/operator_converters/XGBoost.py", line 189, in convert
    name=scope.get_unique_operator_name('TreeEnsembleRegressor'), **attr_pairs)
  File "/home/victor/.cache/pypoetry/virtualenvs/env-51Be8MFl-py3.7/lib/python3.7/site-packages/skl2onnx/common/_container.py", line 383, in add_node
    "".format(op_type, name)) from e
ValueError: Unable to create node 'TreeEnsembleRegressor' with name='TreeEnsembleRegressor'.
```

For the record it works with XGBoost 0.90 and `convert_xgboost` is setup with `skl2onnx.update_registered_converter`.

**Comment by trivialfis** [comment]
I can help taking a look if there's a reproducible script.  Currently it's still RC so we can fix it.

**Comment by victornoel** [comment]
@trivialfis I think https://github.com/onnx/sklearn-onnx/blob/master/tests_onnxmltools/test_xgboost_converters.py should be perfect for this

**Comment by trivialfis** [comment]
Alright.  Will take a look later tonight.  Thanks for the link!

**Comment by trivialfis** [comment]
Got it.  In a recent commit we set all parameters of `def __init__()` to `None`, in order to remove the duplication of default values between Sklearn interface and XGBoost core.  This breaks the converter that relies on `get_param` returning a valid value.

**Comment by trivialfis** [comment]
@victornoel Is it safe to assume users call this function only after `fit` or `load_model`?  If so we can call `save_config` and obtain a complete list of internal parameters: https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html#saving-and-loading-the-internal-parameters-configuration

**Comment by victornoel** [comment]
@trivialfis you mean calling the `convert_sklearn`/`convert_xgboost` functions?

Yes, it is meaningless to convert an unfitted model IMHO, so users should have a model that is already fitted.

**Comment by trivialfis** [comment]
@victornoel Thanks!

**Comment by trivialfis** [comment]
After a fix for the above error, I still got an:

> RuntimeError: Options ['zipmap'] are not registerd for model 'XGBClassifier'.

I'm not sure what it's.  But I passed the test in regressor by a fix.  Will make a PR on XGBoost later.

**Comment by victornoel** [comment]
@trivialfis really great, thanks a lot

**Comment by victornoel** [comment]
> After a fix for the above error, I still got an:
> 
> > RuntimeError: Options ['zipmap'] are not registerd for model 'XGBClassifier'.
> 
> I'm not sure what it's.

@trivialfis I don't understand in the end if things work as expected or not? Is this error fixed by the PR on XGBoost or is it the one I reported? Sorry if I'm being thick :)

**Comment by trivialfis** [comment]
I fixed the error raised in this issue.  But when I run that test file with other tests, I failed the classifier test.

But I also tried other tests from lightGBM and failed many tests.  It seems you have better experience with this project and knows how to run the tests correctly.  So feel free to let me know if there's error seems related to the new release.

**Comment by victornoel** [comment]
@trivialfis ok, I understand, I will do some tests and then close this issue and reopen others in the right projects if needed :)

**Comment by victornoel** [comment]
@trivialfis it seems to work in my setup (I tried latest commit of xgboost branch for the 1.0.0 release), thanks again.
