### ISSUE TITLE
Problem creating onnx file from XGBRanker

### ISSUE THREAD

**Issue by sa-** [onnx/onnxmltools#382]
Hey team. 
I am receiving this:
```
ValueError: No proper operator name found for '<class 'xgboost.core.Booster'>'
```
when trying to serialize a ranking model from xgb.

I train my data using 
```
xgb.train({"objective":"rank:ndcg", "max_depth": 9}, train_xgb)
```

Maybe the `rank` objectives behave differently?

Looks like `XGBRanker` and `Booster` are missing from `xgboost_operator_name_map` https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/xgboost/_parse.py#L16

Since the ranking model outputs a single number, my intuition says serializing it would be similar to an `XGBRegressor`

**Comment by sa-** [comment]
Let me know if I can provide additional details, or help fix the issue in some way

**Comment by wenbingl** [comment]
@xadupre, can you help with it?

**Comment by xadupre** [comment]
I'm currently writing an example for every supported library. XGBoost is already there. See PR #385.

**Comment by sa-** [comment]
It looks like you have an example that works with `'objective': 'multi:softmax'` but not with `'rank:ndcg'`, which is where the bug exists.

**Comment by xadupre** [comment]
Ranking is not supported yet. I need to see first how long it would take to support it.

**Comment by sa-** [comment]
Got it. Can I help scope it out?

**Comment by xadupre** [comment]
You are free to contribute. The first task is to know whether or not the ranker can be modelled with onnx operators and then to modify the code to update the conversion (in this folder: https://github.com/onnx/onnxmltools/tree/master/onnxmltools/convert/xgboost).

**Comment by sa-** [comment]
I am using a workaround for now by loading the model up as an XGBRegressor.

```
model = xgb.XGBRegressor()
model.load_model(...)

initial_types = [('input', FloatTensorType([None, num_features]))]
onnx_output_path = "something.onnx"
onnx_model = onnxmltools.convert_xgboost(model, initial_types=initial_types, doc_string=onnx_output_path)}"

with open(filename, "wb") as f:
    f.write(onnx_model.SerializeToString())
```

**Comment by horiee** [comment]
has it been resolved or suggested to use the workaround? @sa- @xadupre thx

**Comment by PabloBrianese** [comment]
Any updates on this issue?

**Comment by hasush** [comment]
I would also like updates on this issue.

**Comment by hasush** [comment]
The workaround is failing on xgboost 1.7.4 and python 3.9.15.
`
ranker_model = XGBRanker()
... do stuff ...
ranker_model.save_model(fname='path.ubj')
regressor_model = XGBRegressor()
regressor_model.load_model(fname='path.ubj')
>>> TypeError: Loading an estimator with different type. Expecting: regressor, got: ranker
`

**Comment by Man1978-scd** [comment]
I would also like updates on this issue. Ranker model is needed in lightgbm、xgboost and catboost， if has this api，it will be very good
