### ISSUE TITLE
keras 2 onnx

### ISSUE THREAD

**Issue by Echosanmao** [onnx/onnxmltools#390]
onnx_model = onnxmltools.convert_keras(keras_model, target_opset=7) 
When I convert keras model to onnx ,
I want to know how I set target_opset, what is the latest target_opset, target_opset=11?

**Comment by Echosanmao** [comment]
when I convert onnx to mnn:
onnx model ir version 6
check failed:(input_size()==4)||(input_size()==2)==>"onnx resize should have 4 or 2 inputs!"
segmentation fault(core dumped)

**Comment by jiafatom** [comment]
latest target_opset is usually in sync with the onnx that you installed. As for today it is 11, will soon be 12.

you mentioned "onnx to mnn", this is not in keras2onnx scope.

**Comment by Echosanmao** [comment]
> latest target_opset is usually in sync with the onnx that you installed. As for today it is 11, will soon be 12.
> 
> you mentioned "onnx to mnn", this is not in keras2onnx scope.

OK.
Thank you so much and thanks for your reminder.
