### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mcmingchang** [onnx/onnxmltools#420]
![11111](https://user-images.githubusercontent.com/37234299/91682322-bb124000-eb83-11ea-8135-b40ad33fd6ad.png)
![2222](https://user-images.githubusercontent.com/37234299/91682328-bf3e5d80-eb83-11ea-95df-365e2407a00b.png)
When H5 converts onnx, there are more bias

**Comment by xadupre** [comment]
Could you give more insights about this issue? What you tried to do, which model (keras I assume), is there a way to replicate, do you see different outputs with onnx?

**Comment by mcmingchang** [comment]
Sorry, I have forgotten how to do it. This is tf.keras model



---Original---

**Comment by xadupre** [comment]
I would suggest to raise an issue on keras2onnx project.

**Comment by xadupre** [comment]
Closing the issue. You should use tf2onnx. It now converts tensorflow and keras models.
