### ISSUE TITLE
onnxmltools on conda-forge

### ISSUE THREAD

**Issue by jborchma** [onnx/onnxmltools#436]
So I was wondering if it's possible (or already planned) to create a conda package for `onnxmltools`. I assume there are some dependencies like `keras2onnx`, etc. that are still missing. However, `onnx` is already available through conda.

**Comment by janjagusch** [comment]
`onnxmltools` is now on conda-forge: https://anaconda.org/conda-forge/onnxmltools, @jborchma.

**Comment by jborchma** [comment]
That's great! I am going to close the issue then.
