### ISSUE TITLE
Wrong result of the FP32-to-FP16 conversion of Resize op

### ISSUE THREAD

**Issue by ynborokh** [onnx/onnxmltools#446]
There is a problem with the conversion of the FP32 onnx model to FP16.

Step 1. Create a Keras model.

Use the following code:

    inputs = Input(shape=(100, 2))
    pool1 = MaxPooling1D(pool_size=2)(inputs)
    conv1 = Conv1D(32, 3, activation='relu', padding='same')(pool1)
    up1 = UpSampling1D(size=2)(conv1)
    concat1 = Concatenate()([inputs, up1])
    kerasModel = Model(inputs=inputs, outputs=concat1)`

You can find it as `Fail_Keras.hdf5` [here](https://drive.google.com/drive/folders/1_1-ZJqKN0ROPuoGRiNuH1PdBwQPIUiCu).

Step 2. Convert the Keras model to Onnx.

I'm using keras2onnx 1.8.0 revision=4edf53c.

    onnxModel = onnxmltools.convert_keras(kerasModel, target_opset=12)

We obtain a pretty valid onnx model. You can find it as `Fail_FP32_Onnx.onnx` [here](https://drive.google.com/drive/folders/1_1-ZJqKN0ROPuoGRiNuH1PdBwQPIUiCu).

Step 3. Convert the FP32 Onnx model to FP16.

I'm using onnxmltools 1.8.0 revision=ccddab5.

    onnxModelFP16 = convert_float_to_float16(onnxModel);

Conversion completes successfully, and we have a `Fail_FP16_Onnx.onnx` [here](https://drive.google.com/drive/folders/1_1-ZJqKN0ROPuoGRiNuH1PdBwQPIUiCu). But now there is a problem since there are two inputs for `Concat` layer, one of them is FP32, and another is FP16, and `Concat` receives only FP16 inputs.
![fail](https://drive.google.com/uc?export=view&id=1Hq5Bv_9bzShFnDIm9PE_CDsG5wTUghBR).

When we try to load the model by OnnxRuntime the following exception is thrown: `Type Error: Type parameter (T) bound to different types (tensor(float16) and tensor(float) in node (concatenate).`

The problem is somehow caused by the presence of the `Conv` layer (a blue layer on the picture above), because, if we create a Keras model without the convolution layer and make all the same conversions, then we obtain the following FP16 onnx model:
![success](https://drive.google.com/uc?export=view&id=1pz7kQxM5t1BjPQPIBeo6V5lVkVGSK995).

Here we see that after `Resize` `Cast` operation appears, which is missing in the previous model. It converts FP32 input to FP16 output, so `Concat` layer now obtains two inputs in FP16.

You can find these "good" models as `Success_Keras.hdf5`, `Success_FP32_Onnx.onnx` and `Success_FP16_Onnx.onnx` [here](https://drive.google.com/drive/folders/1_1-ZJqKN0ROPuoGRiNuH1PdBwQPIUiCu).

Could you please take a look at this issue?

**Comment by ynborokh** [comment]
This issue disappears after `onnx` dependency is upgraded from `1.7.0` to `1.8.1` .

**Comment by SStarver** [comment]
![image](https://github.com/onnx/onnxmltools/assets/108868933/5cda03bd-b6e7-4ff3-8e42-b9f48206267d)
