### ISSUE TITLE
Release 1.8.0 to Python Package Index

### ISSUE THREAD

**Issue by wbu-wish** [onnx/onnxmltools#472]
According to github [releases](https://github.com/onnx/onnxmltools/releases), 1.8.0 has already been released, which contains [one](https://github.com/onnx/onnxmltools/pull/429) of the bug fixes we need for xgboost conversion.

Please also release it to [PPI](https://pypi.org/project/onnxmltools/) so that the installation can be done smoothly without having to build from source. 

Thanks.

**Comment by xadupre** [comment]
Sorry for the late answer, this should be done shortly.

**Comment by xadupre** [comment]
Closing the issue. Version 1.9.0 was done two days ago.
