### ISSUE TITLE
Support for Spark variable length features

### ISSUE THREAD

**Issue by mhv777** [onnx/onnxmltools#477]
Hello, I was wondering if there's support for variable length features. For example Spark's CountVectorizer can receive a list of strings of different sizes, and perform a sort of One Hot Encoding on the values.

See below:
 
+-----------------------+-------------------+
| csv                                   | output                     |
+-----------------------+-------------------+
|[Val1, Val2]                      | (5,[1,4],[1.0,1.0])     |
|[Val3, Val4]                     | (5,[0,3],[1.0,1.0])     |
|[Val5, Val3]                     | (5,[0,2],[1.0,1.0])     |
|[Val3, Val3, Val3]            | (5,[0],[3.0])             |
+-----------------------+-------------------+

To clarify:
1. Is the CountVectorizer Supported?
2. Is there support for variable length features?
3. Is there support for sparse input? (The only way I could get this to work was transforming the feature vector back into dense, which in my context is unacceptable due to latency constraints)

Thanks in advance to anyone that can answer any of these questions.

**Comment by xadupre** [comment]
CountVectorizer is not supported. There is no support for variable length features. Sparse input is a work in progress. Before being available, ONNX and onnxruntime need to support it. This work is still on going.

**Comment by mhv777** [comment]
Thanks for the response! Will keep an eye on sparse input progress.
