### ISSUE TITLE
Incorrect error message while converting model to onnx format

### ISSUE THREAD

**Issue by cepera-ang** [onnx/onnxmltools#48]
Latest version of onnxmltools has `targeted_onnx = '1.1.2'` and if installed version is 1.1.1 then error message appears 'ONNX version conflict found. The installed version is 1.1.2 while the targeted version is 1.1.1' which is inverse of actual situation. 
https://github.com/onnx/onnxmltools/blob/5f41a2bd185b946de113714910e1f5f2730d5f4b/onnxmltools/convert/common/_topology.py#L607

Also, onnx version in master is 1.1.1 and in pip is 1.1.2 but master is definitely more up to date.

**Comment by wschin** [comment]
Ok. I will extract onnx version from the installed onnx package.

**Comment by cepera-ang** [comment]
As far as I can see, it is already happens, you just need to swap the
variables in line 610 and message will become correct.

**Comment by wschin** [comment]
@cepera-ang , You're right. I also changed the default version because I guess it's better to use the installed onnx version as the default version. What do you  think?

**Comment by cepera-ang** [comment]
Sounds good to me.
