### ISSUE TITLE
convert_lightgbm appears to be stuck in an infinite loop for a multiclass model

### ISSUE THREAD

**Issue by cabillin** [onnx/onnxmltools#482]
Python 3.8.8
onnxmltools 1.7.0 (last we checked, higher versions break the output data type we need--the was bug fixed and then reintroduced)

We have an example that has been running/stuck for 4.5 days.
I started another run yesterday with a debugger attached. When I pause the process, I see a deep stack with modify_tree_for_rule_in_set & it's recursive_call method:
![image](https://user-images.githubusercontent.com/71525014/126539634-75ef2122-2a57-491a-8d34-466bc29a6460.png)

The lightgbm model.txt file is 251MB (Attachment of the full file failed--I assume because it was too big, but I've attached a file containing just the 1st 10 trees. Please reach out for the model.txt if needed for repro).
[multiclass_lgbm_model_truncated_trees.txt](https://github.com/onnx/onnxmltools/files/6858215/multiclass_lgbm_model_truncated_trees.txt)

**Comment by xadupre** [comment]
I was able to convert the first 10 trees. I think there come from another tree. Is it possible to change the following lines in the `lightgbm.py` (see PR #487).

```
    if 'tree_info' in gbm:
        for it, tree in enumerate(gbm['tree_info']):
            print("modify_tree_for_rule_in_set: tree %d" % it)
            modify_tree_for_rule_in_set(tree, use_float=use_float)
        return
```

And copy paste the tree corresponding to the last number. It should be the tree for which the infinite loop happens.
