### ISSUE TITLE
Please verify ONNX v1.10.0 Release Candidate

### ISSUE THREAD

**Issue by rajeevsrao** [onnx/onnxmltools#483]
Hello ONNX partner,
We have published (to TestPyPI) a Release Candidate package for the upcoming ONNX v1.10.0 release. Please help validate it and let us know if you encounter any issues. Note that the tentative release date for ONNX v1.10.0 is July 31, 2021. Thank you for your assistance!

```
pip install numpy protobuf typing-extensions>=3.6.2.1
pip install -i https://test.pypi.org/simple/ onnx==1.9.101
```

* 07/26/2021: RC2 with `make_sequence_value_info` alias - [onnx 1.9.101](https://test.pypi.org/project/onnx/1.9.101/)
* 07/21/2021: RC1 for validation - [onnx 1.9.100](https://test.pypi.org/project/onnx/1.9.100/)

cc @xadupre @wenbingl @wschin

**Comment by rajeevsrao** [comment]
@xadupre @wenbingl @wschin did you get a chance to test RC2? Please let us know at the earliest since we are planning a release end of this week?

**Comment by xadupre** [comment]
I'll do this today.

**Comment by xadupre** [comment]
I verified the package. It works. CI still fails on Windows but the error comes from coremltools. We still use an old version of coremltools. onnx==1.10.0 is ok.
