### ISSUE TITLE
Which coremltools version is supported on onnxmltools?

### ISSUE THREAD

**Issue by adjhawar** [onnx/onnxmltools#486]
I was trying to convert some coreML models to onnx and vice versa using the latest versions of both the packages. However, I was getting errors while trying to convert. While going through the onnxmltools issues for coreML, I found that the onnxmltools package was being tested against coremltools==3.1. So I was just curious to know, if that is still the case?

**Comment by xadupre** [comment]
Unfortunately, yes, we did not have time so far to update the library for more recent versions.
