### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by janjagusch** [onnx/onnxmltools#489]
@xadupre, many things have happened since the last release. Could you please release a new version?

Thanks a lot. 🙂

**Comment by xadupre** [comment]
I'll do that. Just a last bug to fix (support for multiclass Lighgbm booster)

**Comment by janjagusch** [comment]
> I'll do that. Just a last bug to fix (support for multiclass Lighgbm booster)

Thanks!

**Comment by xadupre** [comment]
Closing the issue. Version 1.9.0 was done two days ago.
