### ISSUE TITLE
Can onnxmltool add support for shape override in onnxmltools.convert_tensorflow?

### ISSUE THREAD

**Issue by JingqiaoFu** [onnx/onnxmltools#495]
Some Tensorflow models require specifying shape overrides in input names in order to be converted, would like to have onnxmltools support that.

**Comment by JingqiaoFu** [comment]
Can you publish a release ?

**Comment by xadupre** [comment]
I'll do that this week or the next one. I'd like to merge #496 first.

**Comment by JingqiaoFu** [comment]
> I'll do that this week or the next one. I'd like to merge #496 first.

Just checking again to see any possibility to publish a new release this week? Thanks!

**Comment by xadupre** [comment]
Sorry for being late. onnxruntime 1.9.0 was released last week so I wanted to make sure onnxmltools support opset 15 before doing another release. It should be done by tomorrow.
