### ISSUE TITLE
Update float16 converter api with auto_convert_mixed_precision

### ISSUE THREAD

**Issue by BowenBao** [onnx/onnxmltools#544]
Based on discussion from #543, the feature should be updated to

* Ensure auto_convert_mixed_precision supports large models and
* Ensure auto_convert_mixed_precision runs reasonably fast when there are no underflow / overflow issues, then
* Expose auto_convert_mixed_precision as part of onnxmltools. Stop exposing convert_float_to_float16* as part of onnxmltools

**Comment by garymm** [comment]
@xiaowuhu can you work on this please?

**Comment by xiaowuhu** [comment]
> @xiaowuhu can you work on this please?

sure, let me try.

**Comment by garymm** [comment]
@xadupre can you assign the issue to @xiaowuhu ? (I don't have permission)

**Comment by BowenBao** [comment]
@xiaowuhu Doesn't seem reasonable to me.

**Comment by garymm** [comment]
The CPU EP may be inserting a lot of cast operations under the hood if the CPU op implementations don't support FP16, but it does seem bad that it's so much slower.
Not sure how to find that out other than reading the ORT source code or talking to someone on ORT team.

**Comment by xiaowuhu** [comment]
I will ask tingyeqiaqia about the inference speed. already contact with him yesterday through email.

A quick question, In general, fp16 is going to use in CPU device or GPU device?

**Comment by xiaowuhu** [comment]
this is the investigation result:


![Image](https://user-images.githubusercontent.com/19218188/170419718-035c5917-ae49-40ec-a80a-d430cddb6ded.png)

- CPU,  fp16 is slower than fp32
- GPU,  fp16 run with nan, fp32 works well.

**Comment by garymm** [comment]
It seems like you've done the first 2 points in the original issue description, except maybe confirming that auto_mixed_precision can also **write** large models. Is that correct?
If so, then confirm that it can both read and write large models.
Then do the third point from the issue description.
