### ISSUE TITLE
verify onnx 1.12.0 release candidate

### ISSUE THREAD

**Issue by xiaowuhu** [onnx/onnxmltools#565]
pip install -i https://test.pypi.org/simple/ onnx==1.12.0rc4

**Comment by garymm** [comment]
rc5 is ready now, please use that

**Comment by xiaowuhu** [comment]
when running one function in onnxmltools, failed at:

https://dev.azure.com/onnxmltools/onnxmltools/_build/results?buildId=22164&view=logs&j=49730df0-aed2-55c0-bbd7-2f2e78f1ae25&t=0c6d2d39-456a-5487-6ca3-b833f3608c12&l=325

due to StrictVersion cannot recognize the version format such as 1.12.0rc5. but LooseVersion can.

but from this page: https://peps.python.org/pep-0386/ , seems we need to use the new versioning algorightm.

**Comment by xiaowuhu** [comment]
complete by: https://github.com/onnx/onnxmltools/pull/564

**Comment by garymm** [comment]
Close this then?
