### ISSUE TITLE
Please validate ONNXMLTOOLS with ORT 1.12 release candidate

### ISSUE THREAD

**Issue by fatcat-z** [onnx/onnxmltools#571]
Python (CPU)
https://test.pypi.org/project/ort-nightly/1.12.0.dev20220707003/

Python (GPU)
https://test.pypi.org/project/ort-nightly-gpu/1.12.0.dev20220707003/

**Comment by xiaowuhu** [comment]
done. https://github.com/onnx/onnxmltools/pull/572
