### ISSUE TITLE
Importing onnxmltools implicitly overrides onnx.helper.make_tensor

### ISSUE THREAD

**Issue by jbachurski** [onnx/onnxmltools#575]
Due to the following code in `onnxmltools/proto/__init__.py`:

https://github.com/onnx/onnxmltools/blob/d7db0ffc73e33c6545261dfb72ed69ea12b3d48a/onnxmltools/proto/__init__.py#L24-L50

`onnx.helper.make_tensor` gets overwritten. Hence, any code using `onnxmltools` that also wants to use `make_tensor` is forced to use a more primitive version, since the original is more capable:

https://github.com/onnx/onnx/blob/84f6ff689da8ec930877478d3a50fe5081ad582f/onnx/helper.py#L303-L369

This definitely seems like outdated code (git blame states it's 4 years old) and should probably be removed or at least be less invasive about the injection. 

Currently, importing modules have to perform a similar hack to counteract this behaviour.

**Comment by cbourjau** [comment]
Fixed in cfb2cc0e76947b53dae18d568c44c5f56fa55009 which is not part of the current release, yet.
