### ISSUE TITLE
get rid of `pickle` and `eval`

### ISSUE THREAD

**Issue by KOLANICH** [onnx/onnxmltools#583]
`pickle` and `eval` are security issues and should not be used.

If a usernis OK with them, he must call them themselves.

**Comment by xadupre** [comment]
It is only used for unit testing to allow developer to debug faster when it fails.

**Comment by KOLANICH** [comment]
The problem is they are within the main package, and so they are intalled with it, so importing the harmful modules from `onnxmltools` rather than directly can be used to avoid detection of using those modules within backdoors.

**Comment by xadupre** [comment]
I see what you mean. It should be easy to move in the unit test subtest so that are not part of the main package.

**Comment by xadupre** [comment]
Fixed in #632

**Comment by KOLANICH** [comment]
Thanks.
