### ISSUE TITLE
How to write entirely new converter

### ISSUE THREAD

**Issue by camer314** [onnx/onnxmltools#592]
We have GBM models written in C# using our proprietary algorithms and was wondering if it is possible to convert these to ONNX? 

These models do not use any traditional framework as they are entirely written inhouse.

What would be required to write a converter for these? I cannot seem to find documentation on the process.

**Comment by xiaowuhu** [comment]
@camer314 Hi, this is an PR example for a new converter:
https://github.com/onnx/sklearn-onnx/pull/915

It just care about inference, not cover the training the process.
