### ISSUE TITLE
LightGBM Version 4.0.0 changes

### ISSUE THREAD

**Issue by ksaur** [onnx/onnxmltools#632]
LGBM 4.0.0 was [released](https://github.com/microsoft/LightGBM/releases) 3 days ago and they added an underscore to many things. Ex: `FEATURE_IMPORTANCE_TYPE_MAPPER` becomes `_FEATURE_IMPORTANCE_TYPE_MAPPER`. See https://github.com/microsoft/LightGBM/pull/5654

I think this means that onnxmltools needs to update [LightGbm.py](https://github.com/onnx/onnxmltools/blob/e28140d6ee3f237cfabfa7294a366d41b07727b8/onnxmltools/convert/lightgbm/operator_converters/LightGbm.py#L268): `_LIB, FEATURE_IMPORTANCE_TYPE_MAPPER, _safe_call,` ....

**Comment by xadupre** [comment]
Thanks for reporting it. I'll look into that soon.

**Comment by xadupre** [comment]
PR #634 was merged.
