### ISSUE TITLE
XGBoost 2.0.0 breaking changes

### ISSUE THREAD

**Issue by ksaur** [onnx/onnxmltools#651]
Hi there, XGB 2.0.0 was [released](https://github.com/dmlc/xgboost/releases/tag/v2.0.0) last week (Sept 12, 2023) that breaks some things.

Here is an example:
```

from onnxmltools.convert import convert_xgboost
from onnxmltools.convert.common.data_types import FloatTensorType
import xgboost as xgb

import numpy as np
n_features = 28
n_total = 100
np.random.seed(0)
X = np.random.rand(n_total, n_features)
X = np.array(X, dtype=np.float32)
y = np.random.randint(2, size=n_total)

# Create XGBoost Model
model = xgb.XGBClassifier()
model.fit(X, y)

conv_model = convert_xgboost(model, initial_types=[("input", FloatTensorType(shape=[None, None]))])

```

**with: xgboost==1.7.6**
Output:  No error

**with xgboost==2.0.0**
Output:
`TypeError: unsupported operand type(s) for [//](https://github.com/onnx/onnxmltools/issues/new): 'int' and 'NoneType'`

cc: https://github.com/microsoft/hummingbird/issues/732

**Comment by ParanoidAltoid** [comment]
Found a really pernicious bug where 2.0.0 caused incorrect output, but with no errors.

Running sklearn-onnx's own tutorial on serializing xgboost models fails:
http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_xgboost.html
Downloading the file at the bottom of that page and running with 2.0.0 gives this:
```
predict [162.61285 102.44898 163.59125 112.00508 122.19469]
predict [ 11.50652  -48.65735   12.484911 -39.10126  -28.911642]
```
(Both those should be the same, second is the same model but after serializing.)

Maybe I'm missing something obvious but this was brutal for me. Would a warning be worth adding for 2.0.0 when calling this function until it's fixed?

**Comment by xadupre** [comment]
Your example is passing now.

**Comment by xadupre** [comment]
I'll close the issue.
