### ISSUE TITLE
XGBoost best_ntree_limit is removed in 2.0 and trying to access this value

### ISSUE THREAD

**Issue by hellojunha** [onnx/onnxmltools#668]
best_ntree_limit attribute is removed in XGBoost 2.0 (https://github.com/dmlc/xgboost/pull/8345/files) but onnxmltools is trying to access this attrubute in xgboost/_parse.py:73.
```
72        trees = len(res)
73        ntrees = booster.best_ntree_limit
74        num_class = trees // ntrees
```
Using method for older version looks still working but I am not sure since I am a newbie to machine learning.
Is it ok to create a pull request that fixes this issue using method for older version?

**Comment by xadupre** [comment]
The new version released today should address this issue. Feel free to reopen it if it is not.
