### ISSUE TITLE
RandomForestClassifier: ONNX output converts all BRANCH_LEQ to BRANCH_EQ

### ISSUE THREAD

**Issue by tiago-rib-goncalves** [onnx/onnxmltools#688]
Hey,

After conversion of pyspark.ml RandomForestClassifier to ONNX, when infering with InferenceSession from onnxruntime, all the output probabilities (and, thus, predictions) were the same.

While comparing the output from the ONNX model with the sparkml model, it was noticed that the ONNX model assigned all BRANCH_LEQ nodes to BRANCH_EQ.

Tracing back this issue to _onnxmltools/convert/sparkml/operator_converters/tree_helper.py_, function _rewrite_ids_and_process_, it is possible to see that this is happening since the node values for these nodes are contained in an array (L282).

Going further back, this is due to the _function sparkml_tree_dataset_to_sklearn_ in _onnxmltools/convert/sparkml/operator_converters/tree_ensemble_common.py_. In here, issue appears to be in L31:
```threshold.append(item["leftCategoriesOrThreshold"])```
which is retrieving an array.

Is there any reason to not using:
```threshold.append(item["leftCategoriesOrThreshold"][0] if len(item["leftCategoriesOrThreshold"]) >= 1 else -1.0)```
just like it is done in L37 for the tuple case:
```threshold.append(item[1][0] if len(item[1]) >= 1 else -1.0)```
?

Thank you :)
Best regards,
Tiago

**Comment by xadupre** [comment]
The PR was merged, I'll close this issue.
