### ISSUE TITLE
FeatureUnion and FeatureSelection in scikit-learn

### ISSUE THREAD

**Issue by wschin** [onnx/onnxmltools#84]
We should support [FeatureUnion ](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html) and [FeatureSelection ](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.feature_selection). It's common to apply different pre-processing steps to different parts of the input feature vector. Some of them are able to be converted into ONNX.

**Comment by steadyfish** [comment]
Hi @wschin 

Thanks for building this package. I'm very interested in using this package especially to convert sklearn models to ONNX. One of the key things as you know is being able to use FeatureUnions and Pipelines. 

I was wondering if you have any ETA in mind for this feature being made available.

**Comment by prabhat00155** [comment]
@steadyfish You should be able to use FeatureUnions and Pipelines.
