### ISSUE TITLE
Example from readme does not work

### ISSUE THREAD

**Issue by stared** [onnx/onnxmltools#91]
Example from readme does not work, with the freshest pip-installed version of `onnxmltools`:

```
onnx_model = onnxmltools.convert_keras(keras_model)
```

Results in error:

```
AttributeError: module 'onnxmltools' has no attribute 'convert_keras'
```

Just in case, I have:

* keras: 2.1.4
* onnxmltools: 0.1.0.0000

**Comment by wschin** [comment]
Could you try to install onnxmltools via `pip install git+https://github.com/onnx/onnxmltools` and try again? The pypi package is not updated yet. Thanks.

**Comment by wschin** [comment]
Close it for now because I believe it has been resolved. If it still doesn't work, let's reopen it again. Thank you very much.

**Comment by arindam93** [comment]
I am facing the same problem even when install the toolbox from source.

**Comment by prasanthpul** [comment]
convert_keras is in https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/main.py so if you do pip install git+https://github.com/onnx/onnxmltools you should get it. please verify whether the installation contains the same file as linked above.

**Comment by claguna** [comment]
It works for me after installing from git repo.
Can someone update the readme to let people know this is required?
