### ISSUE TITLE
Padding in Pooling

### ISSUE THREAD

**Issue by wschin** [onnx/onnxmltools#93]
We need to swap [SAME_UPPER and SAME_LOWER](https://apple.github.io/coremltools/coremlspecification/sections/NeuralNetwork.html#samepadding) in [Pooling's converter](https://github.com/onnx/onnxmltools/blob/646ae67c5b989050bde73698e728630c64530e3a/onnxmltools/convert/coreml/operator_converters/neural_network/Pool.py#L222) to match ONNX definition.

**Comment by charanpool** [comment]
For every node in onnx where padding is required, It is either specified directly by "pads" attribute(of that particular node) or through "auto-pad" attribute. If the auto-pad is SAME_UPPER or SAME_LOWER how do we calculate the padding values?
